### ISSUE TITLE
Development Plan or Roadmap

### ISSUE THREAD

**Issue by pathumego** [trufont/trufont#42]
@adrientetar Would be awesome to have dev plan/roadmap or priorities you have in mind :) That way if there is anybody willing to contribute code can think. And would be easier to organise and manage issues according to priorities.

**Comment by davelab6** [comment]
Here are the items from the pre-release issue tracker:

- [ ] glyph transformations support - anything more to do?

- [ ] Complete font info fields

- [ ] copy/paste points w their contour. Later notes by Adrien said "notification rewind is there, just need to implement c/p" and then "can drop the last point on an open contour – I need to consolidate the algorithm."

- [ ] sidebearings dragging in glyphView, so you can drag them as you draw, and then fine-tune in spaceCenter later

- [ ] "having the same keyboard hotkeys for changing metrics in the glyph editor window would also be great" and Adrien replied "glyphView is a lot of mouse usage and also it's just one glyph that you shape so dragging makes more sense. In spaceCenter you can look at a word with its context and fine-tune all glyphs one after the other so batch keyboard processing makes more sense."

- [ ] support kerning editing. Adrien wrote earlier, "I have thought about kerning editing for some time already and actually the built-in UFO kerning facility doesn't support what's called enum in an FEA file, also known as 'group exceptions.' You can only declare pair kerning and you don't have subtables in a UFO, which is limiting for a full-blown kerning editor. So kerning might have to be done separately as e.g. MetricsMachine is doing (and it imports/exports from FEA rather than UFO, though it has the possibility of taking kerning from a UFO as well.)"
- [ ] polish pixmap support
- [ ] QSettings support and dialog (in particular, customising keyboard shortcuts)
- [ ] update to ufo3 defcon (This and supporting all ufo3 attributes are # 1 things to do at the moment.
- [ ] display points coordinates when selected and old outline when moving points
- [ ] tangent points
- [ ] allow dragging sidebearings in glyph editor (also move points when glyph changes, not just contour)
- [ ] allow adding offCurve points to a line segment possible w Ctrl and Shift on onCurve but no double click on segment like glyphsapp yet
- [ ] scale selected w BBox
- [ ] Improved "Add Anchor Point" Dialog. @felipesanches said, "Could provide a combobox with a list of previously used anchor class names for the user to choose, and an option called "New class name" that, when selected, displays a previously hidden text field for the user to provide a new anchor name; there is some initial code for that feature commented out in the AddAnchorDialog class." @adrientetar said, "There’s the possibility to store all commonly used name such as top, bottom, center etc. but then again it’s often a script that’s used to place the bulk of the anchors – the script will e.g. place anchors centered on capHeight for capitals and then you just have to move them in the x-axis manually. Alternatively you may choose to copy-paste them but it takes more time. My point is that you’re not going to add all your anchors one after the other using this dialog so it’s unneeded imo." @moyogo said, "I agree. The anchors should come from a list predefined in a configuration file (system, user or project). It would be nice to have some autocomplete from the list of existing anchors in case one wants to change the name of an anchor."
- [ ] a better scripting window; pre-release note by @adrientetar that said "scripting window is done (though core app APIs not yet done)"

- [ ] A proper plugin system; I guess the first step is to define the extension package convention in the documentation
- [ ] A Mechanic-style extension package manager (that hangs off github repos, so that anyone can 'claim' a feature and develop it in their repo, and 'bleeding edge' users get access to all the ones that have registered with the project's 'official extensions' list, which may be invited to shift to the trufont github org or even in some cases the trufont repo itself to be maintained as 'core.')

**Comment by davelab6** [comment]
Here's a roadmap from the hangout today for trufont v1.0.0 - after that point we can all work in the ecosystem, to do things like a nudget tool, prepolator tool, kerning tool etc.

#### Big tasks (2 weeks or more):

- [ ] A proper plugin system; I guess the first step is to adapt the extension package convention of RoboFont in the documentation; then port the Mechanic extension package manager (that hangs off github repos, so that anyone can 'claim' a feature and develop it in their repo, and 'bleeding edge' users get access to all the ones that have registered with the project's 'official extensions' list, which may be invited to shift to the trufont github org or even in some cases the trufont repo itself to be maintained as 'core.')
- [ ] core: Undo support (@graphicore will write a plan for this)
- [ ] (after afdko integration) Integrate the font compilation toolchain being developed in the in www.github.com/google/roboto repo ttf-generation branch
- [ ] glyphView: extended to edit multiple glyphs, with shaping from harfbuzz and https://github.com/typesupply/compositor
- [ ] glyphView + metricsView: Render a hinting preview mode, with freetype-generated raster images
- [ ] Define what full code documentation will be
- [ ] Define what full project documentation will be

#### Medium tasks (1 week or less):

- [ ] core: Keyboard shortcuts via QSettings dialog (in particular, customising keyboard shortcuts). "having the same keyboard hotkeys for changing metrics in the glyph editor window would also be great" and Adrien replied "glyphView is a lot of mouse usage and also it's just one glyph that you shape so dragging makes more sense. In spaceCenter you can look at a word with its context and fine-tune all glyphs one after the other so batch keyboard processing makes more sense."
- [ ] core: Implement File, Generate using ufo2fdk and libre afdko
- [ ] core: support `testForExternalChanges()` triggered `onFocus()` so that editing in several UFO applications is convenient
- [ ] Inspector Window: complete it - add missing transformations
- [ ] glyphView: refactor tools (#18 @adrientetar will do this)
- [ ] glyphView: canvas to support like Rulers, Smart (Snapping) Guides, https://github.com/FontBureau/fbOpenTools/tree/master/ShowCharacterInfo 
- [ ] glyphView: scale selected w BBox (@felipesanches)
- [ ] glyphView: canvas to support left and right bearing dragging in glyphView, so you can drag them as you draw, and then fine-tune in spaceCenter later. (also move points when glyph changes, not just contour)
- [ ] glyphView: display old outline when moving points
- [ ] glyphView: Enhanced edit mode: edit path by grabbing any part of the path. defconQt currently allows editing curves only by dragging its nodes or its control points. Inkscape does offer an additional way to edit paths by clicking any point along the path curve and dragging it. When the cursor is (in node-edit mode) over the curve, it changes to a hand-icon, indicating that it is possible to drag-edit the curve there. Would be good to have it in defconQt as well.
- [ ] glyphView: polish pixmap support: now you can drop a pixmap in the view, and you get only 1 handle in the bottom right to resize it; its the same sizing mechanism as the points. So could support transforms; also needs a "fit image" function; needs resizing handles on all 4 corners. 
- [ ] glyphView: Improved measurement tool, like the measurement tool in Inkscape, as seen in https://www.youtube.com/watch?v=LjfVyGbHsdc (@felipesanches)
- [ ] glyphView: cursor should change when hovering an editable element: felipe, "when the user hovers the mouse cursor on an editable element such as a node or a control point, the cursor should change to a different icon to provide feedback on what is clickable/interactive and what is not." moyogo "In FontLab the little black square at the bottom right of the cursor arrow changes into a black circle or diamond, and it changes into a dotted rectangle if there is a selection when hovering close to a node or a segment. 

![2667557994-fontlab1](https://cloud.githubusercontent.com/assets/261579/10730415/f2bd7bc2-7bd6-11e5-9826-9d40e79c5355.gif)

![1455817022-fontlab2](https://cloud.githubusercontent.com/assets/261579/10730416/f2bdbe70-7bd6-11e5-86f8-78b36eca405b.gif)

In Glyphs a white square appears at the bottom right of the cursor arrow when hovering close to a node. 

![2439707925-glyphs1](https://cloud.githubusercontent.com/assets/261579/10730414/f2b8b9e8-7bd6-11e5-812a-b3617966fccb.gif)

In BirdFont, on curve nodes change color, getting slightly darker when the arrow hovers close to them.
As far as I know Robofont and Fontforge don’t do this. If the cursor can move a node, distort a curve or pull a line, this kind of feedback can be useful to know what is going to happen. Personally I don’t think I pay much attention to this. I guess by the time I would notice it I’ve already started dragging. I’m thinking something like what BirdFont does isn’t a bad idea: highlight the element that will be modified instead." 

#### Quick tasks (1 day or less):

- [ ] Check that we are supporting all ufo3 attributes
- [ ] glyphView: display points coordinates when selected 
- [ ] glyphView: Tangent points support
- [ ] Basic support for rendering and setting UFOv3 Guidelines
- [ ] Polish the main widgets
- [ ] more interfaces to the internal python APIs
- [ ] Complete font info fields
- [ ] copy/paste points w their contour. Later notes by Adrien said "notification rewind is there, just need to implement c/p" and then "can drop the last point on an open contour – I need to consolidate the algorithm."
- [ ] Improved "Add Anchor Point" Dialog. @felipesanches said, "Could provide a combobox with a list of previously used anchor class names for the user to choose, and an option called "New class name" that, when selected, displays a previously hidden text field for the user to provide a new anchor name; there is some initial code for that feature commented out in the AddAnchorDialog class." @adrientetar said, "There’s the possibility to store all commonly used name such as top, bottom, center etc. but then again it’s often a script that’s used to place the bulk of the anchors – the script will e.g. place anchors centered on capHeight for capitals and then you just have to move them in the x-axis manually. Alternatively you may choose to copy-paste them but it takes more time. My point is that you’re not going to add all your anchors one after the other using this dialog so it’s unneeded imo." @moyogo said, "I agree. The anchors should come from a list predefined in a configuration file (system, user or project). It would be nice to have some autocomplete from the list of existing anchors in case one wants to change the name of an anchor."
- [ ] a better scripting window; pre-release note by @adrientetar that said "scripting window is done (though core app APIs not yet done)"
- [ ] allow adding offCurve points to a line segment possible w Ctrl and Shift on onCurve but no double click on segment like glyphsapp yet

"batteries included" extensions to develop in github.com/trufont:

- [ ] Enhanced edit mode: (@felipesanches will work on this) proportionally change neighbour handles. @marcelommp described a nice feature that FontForge has for editing paths. It is an optional edit mode. It allows one to edit a node while having the control points of the neighbour paths being automatically adjusted in a proportional manner. Marcelo told us that it is a good tool for some type design use-case scenarios such as when creating different weights for a specific glyph. I said "The correct term for this is "Interpolated Nudge" and there are freely licensed python scripts for RoboFont for this. https://github.com/klaavo/scalingEditTool seems to be the best, its MIT. http://tktype.tumblr.com/post/15254264845/interpolated-nudge-for-robofont is more simple, and https://gist.github.com/gferreira/1558831 is a GUI for it. https://vimeo.com/34546631 shows it in use. http://okaytype.com/crypt/ted-nudget-b3.py might be ok, license is unclear." Adrien said "Agreed with all that's been said here, it's very useful when making type. Also scalingEditTool is quite the reference for robofont. When I did think about that I had an unresolved question: should it be part of the selection tool with a switch or be another tool that subclasses the default selection tool? The robofont paradigm is the latter and allows modularity."
- [ ] support kerning editing (@adrientetar wants to do this as a separate program, after trufont v1.0.0 is shipped.) Adrien wrote pre-release, "I have thought about kerning editing for some time already and actually the built-in UFO kerning facility doesn't support what's called enum in an FEA file, also known as 'group exceptions.' You can only declare pair kerning and you don't have subtables in a UFO, which is limiting for a full-blown kerning editor. So kerning might have to be done separately as e.g. MetricsMachine is doing (and it imports/exports from FEA rather than UFO, though it has the possibility of taking kerning from a UFO as well.)"
