### ISSUE TITLE
Document how to build the app packages

### ISSUE THREAD

**Issue by davelab6** [trufont/trufont#53]
@adrientetar please could you provide documentation on how to reproduce the following packages? :) 
- [x] TruFont-X-darwin-10.9.5-x64.zip
- [x] TruFont-X-darwin-x64.zip
- [ ] TruFont-X-gnu-x86.zip
- [ ] TruFont-X-win32-x86.zip

Update:

I chatted with Adrien on 2017-03-27 and he said, 

> I want to make a trufont-pkg repository with a script that does everything it takes to build the packages and holds the data (e.g. manifest for Mac) but it's not done yet

**Comment by adrientetar** [comment]
Lib/build.sh

**Comment by davelab6** [comment]
How did you handle the 10.9.5 / x64 versions?

**Comment by adrientetar** [comment]
By booting on OSX 10.9.5.
